name: Build test and deploy to neocities

on:
  push:
    branches:
      - live-test

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - uses: actions/setup-node@v4
      with:
        node-version: 22.5.1
    - name: install python requirements 
      run: pip install -r data/requirements.txt
    - name: run csv parser
      run: python data/run.py dbexport.csv data-json.mustache data.json
    - run: npm install
    - name: run webpack
      run: npm run build
    - run: mkdir -p public/test/dist
    - name: copy files to test folder
      run: cp style.css index.html public/test
    - name: copy bundle to correct folder
      run: cp dist/bundle.js public/test/dist
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public