name: Build sit and deploy to neocities

on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - uses: actions/setup-node@v4
      with:
        node-version: 22.5.1
    - name: install python requirements 
      run: pip install -r data/requirements.txt
    - name: run csv parser
      run: python data/run.py dbexport.csv data/data-json.mustache data.json
    - run: npm install
    - name: run webpack
      run: npm run build-prod
    - run: mkdir -p public/dist
    - run: mkdir -p public/favicon
    - name: copy files to folder
      run: cp style.css index.html Songbook.pdf public
    - name: copy bundle to correct folder
      run: cp dist/bundle.js public/dist
    - name: copy favicons
      run: cp favicon/* public/favicon/
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public